Fix build error,
FAILED: ninja: 'device/tecno/TECNO_pova5/fstab.mt6833', needed by 'out/target/product/TECNO_pova5/recovery/root/first_stage_ramdisk/fstab.mt6833', missing and no known rule to make it
21:16:54 ninja failed with: exit status 1
Error: Process completed with exit code 1.